/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useState } from "react";

const Home: NextPage = () => {
  const results = trpc.openAI.getResults.useMutation();
  const [show, setShow] = useState("Mad Men from AMC");
  const [thing, setThing] = useState("furniture and decorations");
  const [openAIResponse, setOpenAIResponse] = useState([]);

  const handleSubmit = async () => {
    const response = (await results.mutateAsync({ show, thing })) as any;
    console.log(response);
    setOpenAIResponse(JSON.parse(response?.message?.content));
  };

  return (
    <>
      <Head>
        <title>SYF Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          SYF <span className="text-purple-300">Hack</span>athon
        </h1>
        <div className="mt-2">
          <span className="text-lg text-gray-900">
            Hi Jane, try shopping for{" "}
            <select
              name="thing"
              className="mt-1 mr-2 w-58 rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500"
              value={thing}
              onChange={(e) => setThing(e.currentTarget.value)}
            >
              <option value="furniture and decorations">
                furniture and decorations
              </option>
              <option value="clothes">clothes</option>
              <option value="jewelry">jewelry</option>
            </select>{" "}
            based on{" "}
            <select
              name="thing"
              className="mt-1 mr-2 w-58 rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500"
              value={show}
              onChange={(e) => setShow(e.currentTarget.value)}
            >
              <option value="Mad Men from AMC">Mad Men</option>
              <option value="Star Wars">Star Wars</option>
              <option value="Downtown Abbey">Downtown Abbey</option>
              <option value="Mamma Mia!">Mamma Mia!</option>
              <option value="Legally Blonde">Legally Blonde</option>

              <option value="Stranger Things">Stranger Things</option>

              <option value="Grand Budapest Hotel">Wes Anderson</option>

              <option value="Super Mario Brothers">Super Mario Brothers</option>

              <option value="The Kardashians">The Kardashians</option>

              <option value="Game of Thrones">Game of Thrones</option>
            </select>{" "}
            from Synchrony Vendors.
          </span>

          <div className="flex justify-end">
            <button
              onClick={handleSubmit}
              disabled={results.isLoading}
              className="alrounded-md mt-2 block rounded-md border-transparent bg-gradient-to-r from-orange-600 to-pink-500 px-4 py-3 text-center font-medium text-white shadow hover:bg-gray-700"
            >
              Get some results!
            </button>
          </div>
          {openAIResponse ? (
            <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
              <h2 id="products-heading" className="sr-only">
                Products
              </h2>

              <div className="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
                {openAIResponse.map((product: any, index) => (
                  <a key={index} href={product.link} className="group">
                    <div className="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg sm:aspect-h-3 sm:aspect-w-2">
                      <img
                        src={product.imageSrc}
                        alt={product.item}
                        className="h-full w-full object-cover object-center group-hover:opacity-75"
                      />
                    </div>
                    <div className="mt-4 flex items-center justify-between text-base font-medium text-gray-900">
                      <h3>{product.item}</h3>
                    </div>
                  </a>
                ))}
              </div>
            </div>
          ) : null}
        </div>
      </main>
    </>
  );
};

export default Home;
