import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useState } from "react";

const Home: NextPage = () => {
  const results = trpc.openAI.getResults.useMutation();
  const [show, setShow] = useState("Mad Men from AMC");
  const [thing, setThing] = useState("furniture and decorations");
  const [openAIResponse, setOpenAIResponse] = useState("");

  const handleSubmit = async () => {
    const response = (await results.mutateAsync({ show, thing })) as any;
    console.log(response);
    setOpenAIResponse(response?.message?.content);
  };

  return (
    <>
      <Head>
        <title>SYF Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          SYF <span className="text-purple-300">Hack</span>athon
        </h1>
        <div className="mt-2">
          <span className="text-lg text-gray-900">
            Hi Jane, try shopping for{" "}
            <select
              name="thing"
              className="mt-1 mr-2 w-58 rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500"
              value={thing}
              onChange={(e) => setThing(e.currentTarget.value)}
            >
              <option value="furniture and decorations">
                furniture and decorations
              </option>
              <option value="clothes">clothes</option>
              <option value="jewelry">jewelry</option>
            </select>{" "}
            based on{" "}
            <select
              name="thing"
              className="mt-1 mr-2 w-58 rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-indigo-500"
              value={show}
              onChange={(e) => setShow(e.currentTarget.value)}
            >
              <option value="Mad Men from AMC">Mad Men</option>
              <option value="Star Wars">Star Wars</option>
              <option value="Downtown Abbey">Downtown Abbey</option>
              <option value="Mamma Mia!">Mamma Mia!</option>
              <option value="Legally Blonde">Legally Blonde</option>

              <option value="Stranger Things">Stranger Things</option>

              <option value="Grand Budapest Hotel">Wes Anderson</option>

              <option value="Super Mario Brothers">Super Mario Brothers</option>

              <option value="The Kardashians">The Kardashians</option>

              <option value="Game of Thrones">Game of Thrones</option>
            </select>{" "}
            from Synchrony Vendors.
          </span>

          <div className="flex justify-end">
            <button
              onClick={handleSubmit}
              className="alrounded-md mt-2 block rounded-md border-transparent bg-gradient-to-r from-orange-600 to-pink-500 px-4 py-3 text-center font-medium text-white shadow hover:bg-gray-700"
            >
              Get some results!
            </button>
          </div>
          {openAIResponse ? <span>openAIResponse</span> : null}
        </div>
      </main>
    </>
  );
};

export default Home;
